### PR TITLE
Merged all pull requests.

### PR DESCRIPTION
**Pull request by Daniel-KM**

### CODE REVIEW

**Comment by patrickmj** [comment]
Thanks. I'm continuing to work my way through the changes.

One thing that I noticed is that the translation stuff doesn't work across multiple lines. So for example in `ImportForm` the `autoMapWithLablesOnly` info field probably gets added to the template.pot file, but only as two different strings, and so at the end the translations don't necessarily match up. Looks like it requires an annoyingly long line of text, but I don't see how to avoid that.

We'll be starting some additional user testing within the next week for changes here and for double-checking regressions due to core changes. We'll call a code-freeze here on core pretty soon, and so we should also call a code-freeze on modules. I'll pull in all of your enhancements that you think are ready for our internal user testing. That'll be within the next week, though I can't define a specific date yet.

**Comment by Daniel-KM** [comment]
Ok. For the translation, I prefer short strings, in particular when there is a common part, but I don't like to define a variable just for a translation, so I updated with long strings.

For me, the main points are stable, except the logging part, that requires a change in the table (replacing added_count by an array), but I'm working on some other modules currently and I don't have the time to improve it for now.

**Comment by Daniel-KM** [comment]
In the case you don't want all commits, this is probably simpler to take the whole and to add some triggers.

I updated the readme and the module ini too, but I see you choose to centralize the end user doc. From my point of view, the one doesn't exclude the other.

**Comment by patrickmj** [comment]
Many thanks, as always. We needed to get a release candidate of the core out this week, which required bumping all the themes and modules up to RC as well. (It's not a perfect match with good semantic versioning principles, but we decided that was worth getting everything on a baseline). The upshot here is that this PR didn't make it in to the release, but will come in soon.

**Comment by Daniel-KM** [comment]
Added import of resources (item sets, items and media) in bulk and improved logs.

**Comment by patrickmj** [comment]
Thanks. There's a lot that we still want to look through and test, so sadly I don't think it will all get into the release that will go along with the Omeka S first release. But, as we go along we'll test and pull things in. There are some UI and UX questions that we're thinking about. Generally, we try to keep more advanced/complicated/rare option as hidden as possible, only exposing them optionally. As our testing team goes through all the new features, we'll likely either have suggestions or, if they are easy to add, just put them in from our end.

**Comment by Daniel-KM** [comment]
Ok. Just say me what you want inside and outside the module. 

I'm finishing a small update too to replace CSVFile by a more generic class, so it's possible to import from LibreOffice directly, without issue from Excel non-standard encoding.

**Comment by Daniel-KM** [comment]
I added the possibility to import directly [TSV](https://en.wikipedia.org/wiki/Tab-separated_values) (tab separated value) (https://github.com/omeka-s-modules/CSVImport/pull/105/commits/eef88daf30775dbada50cacff71f851ca44a3634) and [ODS](http://opendocumentformat.org/aboutODF) (OpenDocument Spreadsheet) (https://github.com/omeka-s-modules/CSVImport/pull/105/commits/e9c77cb71a10acd63cf3efd617e90ae2f14938c0).

Note that there is now a dependency, so I added a gulp task to create the zip.

**Comment by patrickmj** [comment]
Is your Folksonomy module ready to be integrated into the testing and features? The readme on the PR seems so, but the link goes to a 404. If we're to pull it all in we should probably have that module published on omeka.org as well.

**Comment by zerocrates** [comment]
We're (back, again) into the process of closing and working out the issues on the current form of our "ui-improvements" branch with an eye toward releasing it.

I'd say chances are low for a straight merge of this PR, at least at the moment, but I'm going to be looking at the specific pieces of it for cherry-pick or similar inclusion to fix specific issues.

Of course, things will still be open to more potential sweeping change after we've finally finished dealing with what we've got now. And once we've finally made a merge and release of our hundreds of WIP commits it should be easier to deal with PRs going forward.

**Comment by Daniel-KM** [comment]
Of course, this is a merge request, and it is based on ui-improvements.
It is possible to create separated pull requests. but, it's harder when they are many, so I'm waiting for integration of some of them.

**Comment by oupala** [comment]
Please accept this merge request as it should allow to import tags as well as contents.

**Comment by oupala** [comment]
This pull request takes so long to get merged that it now requires to resolve new conflict.

Can anyone tell me if this pull request will be merged one day?

Importing tags from a csv file is not possible until this is merged.

**Comment by zerocrates** [comment]
The great majority of this request is already merged and is in the develop branch. In particular, I'm fairly certain all the components that affect compatibility with other modules are merged.

**Comment by oupala** [comment]
How can we use and install a develop version of a module?

**Comment by zerocrates** [comment]
Version 2.0.0 of CSV Import (finally) contains the updates from these pull requests... File Sideload and Mapping have new releases also to correspond.

We don't have every single change from here... I'll be closing these old PRs but changes are still of course welcome as new PRs, including things we didn't take but were previously submitted.

**Comment by oupala** [comment]
Great news! Thanks @Daniel-KM and @zerocrates

**Pull request closed without merging**
