### PR TITLE
Fixes and improvements

### LINKED ISSUE #110: Imported media becomes default
When I manually add new media to an item, it appears below existing media in the sidebar, and the first-added item serves as the representative item for the thumbnail when browsing. However, using the CSV Import to add media does the opposite - the last item imported becomes the representative image, supplanting any existing media already attached, and the order in which media appear in the item's sidebar is reversed from usual (most recently added is at the top, not the bottom).

### PR DESCRIPTION
**Pull request by Daniel-KM**
Fixed #110, and added import of resources (item sets, items and media) in bulk and improved logs.

This is the request for branch daniellkm.

### CODE REVIEW

**Comment by patrickmj** [comment]
When I run the tests locally, I'm getting a series of errors like

```
/var/www/html/omekas/modules/CSVImport/test/CsvImportTest/Job/ImportTest.php:213

22) CSVImportTest\Mvc\Controller\Plugin\ImportTest::testPerformUpdate with data set #13 ('test_update_m_update.tsv', array('items', 1))
Failed asserting that two arrays are equal.

```

**Comment by patrickmj** [comment]
When importing Media, on the Import settings, there's a button for "Set item", which only seems to create an alert warning asking for an identifier. I can't really tell whether that should come from the select above it or not.

Either way, since it looks like it is required that an Item is set somehow, it should not be possible to start the import without that data being set.

**Comment by patrickmj** [comment]
Looks like dropdown to select an Item Id, then hitting the button works. But, the button right at the top for "Internal Id" looks like it should do the same thing, but doesn't appear to work as expected. Using just that, I get the same error in the log that an Item id has not been set.

**Comment by patrickmj** [comment]
It might just be terminology confusion, but I'm not sure what the "Resource" import type is intended to do. Is this a Resource of some sort that is not an Item, Item Set, or Media (the way those are all subclasses of Resource), or something else? Thanks.

**Comment by Daniel-KM** [comment]
In fact, I use it mainly via the automated process : all my files are standardized with good headers (or mappable headers because some people don't want to change their headers), and all the columns are mapped automatically, so I didn't check a lot the second tab of the mapping form.

- For the first point, I use `php phpunit-6.4.phar` and I don't have any error. Which version do you use?
- For the second point, the identifier of the item is required only for creation, not for update. So the button allows to set the item identifier (generally dcterms one). 
- For the third point, the internal id is for the media if you import media, or item if you import item.
- For the fourth point, resources are what you say, but it allows to import multiple types of resource in one file. This is a common requirement when files have metadata, not only items.
I can't check your points now, so next week.

**Pull request merged**
